-- Add is_ai_generated column to sms_messages table
ALTER TABLE sms_messages
ADD COLUMN IF NOT EXISTS is_ai_generated BOOLEAN DEFAULT FALSE;

COMMENT ON COLUMN sms_messages.is_ai_generated IS 'Whether this message was generated by AI (true) or sent by the user (false)';