-- Backfill is_ai_generated for existing messages
-- All outbound messages that were created before this migration are AI-generated
-- (We didn't have user-sent messages before implementing that feature)
UPDATE sms_messages
SET is_ai_generated = true
WHERE direction = 'outbound'
AND is_ai_generated = false
AND created_at < '2025-09-29 19:30:00'::timestamptz; -- Before we deployed send-user-sms with is_ai_generated

COMMENT ON COLUMN sms_messages.is_ai_generated IS 'Whether this message was generated by AI (true) or sent by the user (false)';